server.port=8080
spring.web.cors.allowed-origins=https://tovrean.loengpheaktra.xyz
spring.data.mongodb.uri=${MONGO_URI}
# Change this to your actual database name (e.g., school_supply_db)
spring.data.mongodb.database=e_commerce

# JWT Configuration
app.jwt.secret=${JWT_SECRET}
app.jwt.exp=86400000